services: 

  fastapi:
    image: fastapi
    build: ./fastapi
    volumes:
      - ./fastapi:/app
    ports:
      - 8000:8000
    environment:
      - SQLITE_URL=sqlite:///app/diary.db
      # Replace the SECRET_KEY with a new one. Use this command in a bash terminal: openssl rand -hex 32
      - SECRET_KEY=02c0251715f94313f47ba9cf7309dc2956ff2604a87518c7c8fb338db9df75ca
      - PORT=8000

      
  jaeger:
    image: jaegertracing/all-in-one
    ports:
        - "16686:16686"
        - "6831:6831/udp"  
      
    
            
            
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    build: ./grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000