"""baseline

Revision ID: 73e046ff2fd0
Revises: 
Create Date: 2021-07-28 10:11:45.345299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e046ff2fd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('emotion', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('love', sa.Float(), nullable=True),
    sa.Column('caring', sa.Float(), nullable=True),
    sa.Column('admiration', sa.Float(), nullable=True),
    sa.Column('approval', sa.Float(), nullable=True),
    sa.Column('gratitude', sa.Float(), nullable=True),
    sa.Column('realization', sa.Float(), nullable=True),
    sa.Column('pride', sa.Float(), nullable=True),
    sa.Column('desire', sa.Float(), nullable=True),
    sa.Column('joy', sa.Float(), nullable=True),
    sa.Column('optimism', sa.Float(), nullable=True),
    sa.Column('relief', sa.Float(), nullable=True),
    sa.Column('excitement', sa.Float(), nullable=True),
    sa.Column('neutral', sa.Float(), nullable=True),
    sa.Column('surprise', sa.Float(), nullable=True),
    sa.Column('curiosity', sa.Float(), nullable=True),
    sa.Column('remorse', sa.Float(), nullable=True),
    sa.Column('amusement', sa.Float(), nullable=True),
    sa.Column('grief', sa.Float(), nullable=True),
    sa.Column('nervousness', sa.Float(), nullable=True),
    sa.Column('confusion', sa.Float(), nullable=True),
    sa.Column('sadness', sa.Float(), nullable=True),
    sa.Column('fear', sa.Float(), nullable=True),
    sa.Column('embarrassment', sa.Float(), nullable=True),
    sa.Column('disapproval', sa.Float(), nullable=True),
    sa.Column('annoyance', sa.Float(), nullable=True),
    sa.Column('anger', sa.Float(), nullable=True),
    sa.Column('disgust', sa.Float(), nullable=True),
    sa.Column('disappointment', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_id'), 'post', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
